MvcOAuthUsuarios/Models/BlobModel.cs
namespace MvcOAuthUsuarios.Models
{
    public class BlobModel
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Contenedor { get; set; }
    }
}

MvcOAuthUsuarios/Models/ErrorViewModel.cs
namespace MvcOAuthUsuarios.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcOAuthUsuarios/Models/LoginModel.cs
namespace MvcOAuthUsuarios.Models
{
    public class LoginModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }

    }
}

MvcOAuthUsuarios/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcOAuthUsuarios.Models
{

    [Table("USUARIOSCUBO")]
    public class Usuario
    {

        [Key]
        [Column("ID_USUARIO")]
        public int IdUsuario { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("EMAIL")]
        public string Email { get; set; }
        [Column("PASS")]
        public string Password { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MvcOAuthUsuarios/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcOAuthUsuarios.Models;
using System.Diagnostics;

namespace MvcOAuthUsuarios.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcOAuthUsuarios/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcOAuthUsuarios.Services;
using System.Security.Claims;

namespace MvcOAuthUsuarios.Controllers
{
    public class ManagedController : Controller
    {

        private ServiceApiUsuario service;
        private ServiceStorageBlobs serviceblobs;

        public ManagedController(ServiceApiUsuario service, ServiceStorageBlobs serviceblobs)
        {
            this.service = service;
            this.serviceblobs = serviceblobs;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            string token = await this.service.GetTokenAsync(username, password);

            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
            }
            else
            {
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, 
                    ClaimTypes.Name, ClaimTypes.Role);

                identity.AddClaim(new Claim(ClaimTypes.Name, username));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, password));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        userPrincipal, new AuthenticationProperties
                        {
                            ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30)
                        });
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(string nombre, string email,  string password, IFormFile file)
        {
            string blobName = file.FileName;
            using (Stream stream = file.OpenReadStream())
            {
                await this.serviceblobs.UploadBlobAsync
                ("imagenesrestaurante", blobName, stream);

            }

            await this.service.GetRegisterUserAsync(nombre, email,  password, blobName);

            return RedirectToAction("Login");
        }
    }
}

MvcOAuthUsuarios/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcOAuthUsuarios.Filters;
using MvcOAuthUsuarios.Models;
using MvcOAuthUsuarios.Services;


namespace MvcOAuthUsuarios.Controllers
{
    public class UsuariosController : Controller
    {
        private ServiceApiUsuario service;
        private ServiceStorageBlobs serviceblob;

        public UsuariosController(ServiceApiUsuario service, ServiceStorageBlobs serviceblob)
        {
            this.service = service;
            this.serviceblob = serviceblob;
        }



        [AuthorizeUsers]
        public IActionResult Index()
        {
            return View();
        }

        [AuthorizeUsers]
        public async Task<IActionResult> Perfil()
        {
            string token =
                HttpContext.Session.GetString("TOKEN");
            Usuario usuario = await
                this.service.GetPerfilUsuarioAsync(token);
            BlobModel blobPerfil = await this.serviceblob.FindBlobPerfil("imagenesrestaurante", usuario.Imagen , usuario.Nombre);
            ViewData["IMAGEN_PERFIL"]= blobPerfil;
            return View(usuario);
        }

       

        


    }
}

MvcOAuthUsuarios/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcOAuthUsuarios/Views/Managed/Login.cshtml
<h1 style="color:blue">
    Log In
</h1>

<form method="post">
    <label>Usuario</label>
    <input type="text" name="username" placeholder="User Name" class="form-control" />

    <label>Password</label>
    <input type="text" name="password" placeholder="Password" class="form-control" />

    <button class="btn btn-info">
        Log In
    </button>

</form>

@if (ViewData["MENSAJE"] != null)
{
    <h2 style="color:orangered">
        @ViewData["MENSAJE"]
    </h2>
}

MvcOAuthUsuarios/Views/Managed/Register.cshtml
@model MvcOAuthUsuarios.Models.Usuario

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>
<h4>Usuario</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input type="hidden" asp-for="IdUsuario" class="form-control" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <label>Seleccione un fichero</label>
            <input type="file" name="file" class="form-control"/>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcOAuthUsuarios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcOAuthUsuarios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcOAuthUsuarios.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcOAuthUsuarios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcOAuthUsuarios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcOAuthUsuarios/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated)
{

    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Perfil">Mi Perfil</a>
   


    <a class="nav-link" asp-controller="Managed" asp-action="Logout">
        Log Out
        <span style="color:blue">@Context.User.Identity.Name</span>
    </a>
}
else
{
    <a class="nav-link text-danger" asp-controller="Managed" asp-action="Register">
        Register
    </a>
    <a class="nav-link text-danger" asp-controller="Usuarios" asp-action="Index">
        Log In
    </a>
}

MvcOAuthUsuarios/Views/Usuarios/Perfil.cshtml
@model MvcOAuthUsuarios.Models.Usuario

@{
    ViewData["Title"] = "Perfil";
    BlobModel imgPerfil = ViewData["IMAGEN_PERFIL"] as BlobModel;
}

<h1>Perfil</h1>



<div>
    <h4>Usuario: </h4>
    @if (Context.User.Identity.IsAuthenticated)
    {
        <a class="btn btn-dark" asp-controller="Managed" asp-action="Logout">
            Log Out
            <span style="color:yellow">@Context.User.Identity.Name</span>
        </a>
    }
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>

    <img src="@imgPerfil.Url" style="height:150px" />
</div>